apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-hpa-to-deployments
spec:
  background: false
  rules:
  - name: add-hpa-to-deployment
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchesJson6902:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: "{{request.object.metadata.name}}"
        patch: |-
          - op: add
            path: /spec/scaleTargetRef
            value:
              apiVersion: apps/v1
              kind: Deployment
              name: "{{request.object.metadata.name}}"
          - op: add
            path: /spec/minReplicas
            value: 1
          - op: add
            path: /spec/maxReplicas
            value: 3
          - op: add
            path: /spec/targetCPUUtilizationPercentage
            value: 50
