---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-hpa-on-deployment-creation
  annotations:
    policies.kyverno.io/title: Require HPA on Deployment
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      HorizontalPodAutoscaler is a Kubernetes resource that automatically scales the number of pods in a 
      deployment or replica set based on observed CPU utilization or other custom metrics.
spec:
  rules:
    - name: generate-hpa-on-deployment-creation
      match:
        any:
          - resources:
              kinds:
                - Deployment
      generate:
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        name: "{{request.object.metadata.name}}-hpa"
        synchronize: true
        namespace: "{{request.object.metadata.namespace}}"
        data:
          spec:
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: "{{request.object.metadata.name}}"
            minReplicas: 1
            maxReplicas: 5
            targetCPUUtilizationPercentage: 50
