apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-hpa-on-deployment-creation
spec:
  background: true
  rules:
  - name: generate-hpa-on-deployment-creation
    match:
      resources:
        kinds:
        - Deployment
    generate:
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      name: "{{request.object.metadata.name}}-hpa"
      namespace: "{{request.object.metadata.namespace}}"
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: "{{request.object.metadata.name}}"
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 50
