apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-hpa-to-deployment
spec:
  background: false
  rules:
  - name: add-hpa-to-deployment
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            autoscaling.alpha.kubernetes.io/conditions: '[]'
            autoscaling.alpha.kubernetes.io/current-metrics: '[]'
            autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"averageUtilization":50,"type":"Utilization"}}}]'
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: '{{name}}'
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 50
